name: crea feed RSS c_h933

on:
#  push:
  repository_dispatch:
  schedule:
    - cron:  '27 8,14,19 */1 * *'
  workflow_dispatch:

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Utilizza l'action github checkout@v2, per automatizzare il check-out
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: crea cartella utente bin, copia dentro l'eseguibile di miller, installa xmlstarlet, uv, scrape-cli e yq
      run: |-
        mkdir -p ~/bin
        cp bin/mlr_6 ~/bin/mlr
        cd ~/bin
        chmod +x mlr
        sudo apt-get install xmlstarlet
        curl -LsSf https://astral.sh/uv/install.sh | sh
        uv tool install scrape-cli
        pip install --user yq
    - name: scarica i dati e crea feed
      env:
        SUPER_SECRET: ${{ secrets.IFTTT }}
      run: |-
        export PATH=$PATH:~/bin
        cd ./c_h933
        chmod +x ./c_h933.sh
        ./c_h933.sh
    - name: Committa e pusha se ci sono variazioni nei dati
      run: |-
        git config user.name "automatico"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date --iso-8601=seconds)
        git commit -m "c_h933, San Giuseppe Jato: ${timestamp}" || exit 0
        git push
