name: crea feed RSS c_i725

on:
#  push:
  repository_dispatch:
  schedule:
    - cron:  '10 8,10,13,16 */1 * *'
  workflow_dispatch:

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Utilizza l'action github checkout@v2, per automatizzare il check-out
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: crea cartella utente bin, copia dentro l'eseguibile di rsspls
      run: |-
        mkdir -p ~/bin
        cp bin/rsspls ~/bin
        cd ~/bin
        chmod +x rsspls
        sudo apt install tor
        sudo sh -c "echo 'SOCKSPort 9050 # Default' >> /etc/tor/torrc"
        sudo sh -c "echo 'ExitNodes {it} StrictNodes 1' >> /etc/tor/torrc"
        sudo systemctl start tor
        sudo service tor stop
        sudo service tor start
        wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
        sudo apt-get update
        sudo apt-get install google-chrome-stable
    - name: scarica i dati e crea feed
      env:
        SUPER_SECRET: ${{ secrets.IFTTT }}
      run: |-
        export PATH=$PATH:~/bin
        cd ./c_i725
        google-chrome-stable --headless --disable-gpu --print-to-stdout --virtual-time-budget=10000 --dump-dom "https://siderno.trasparenza-valutazione-merito.it/web/trasparenza/papca-ap/-/papca/igrid/1074/770" >tmp.html
#        chmod +x ./c_i725.sh
#        ./c_i725.sh
    - name: Committa e pusha se ci sono variazioni nei dati
      run: |-
        git config user.name "automatico"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date --iso-8601=seconds)
        git commit -m "c_i725, Siderno: ${timestamp}" || exit 0
        git push
